apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influx:8086
    jsonData:
      version: Flux
      organization: ComputerScience
      defaultBucket: smart-cars
    secureJsonData:
      token: b802c3a5-9f3f-41b3-8be7-f9bc43df5fb8
