{
 "title": "Smart cars monitor",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "licenseplates",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"licensePlate\",\n    predicate: (r) => true,\n    start: 0\n)"
   },
   {
    "name": "timeinterval",
    "query": "'2s','30s','1m', '10m','30m','1h','6h','12h','1d','7d','14d','30d'"
   }
  ]
 },
 "panels": [
  {
   "title": "Localize",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"acceleration\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel\")"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"licensePlate\", \"latitude\", \"longitude\"])\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"smart-cars\")\n  |> range(start: -${timeinterval}, stop: now())\n  |> filter(fn: (r) => r._measurement == \"vehicle\" and contains(value: r.licensePlate, set: ${licenseplates:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")"
    }
   ]
  }
 ]
}